# This workflow will triage pull requests and apply a label based on the
# paths that are modified in the pull request.
#
# To use this workflow, you will need to set up a .github/labeler.yml
# file with configuration.  For more information, see:
# https://github.com/actions/labeler

name: "Pull Request Labeler"

on:
  workflow_call:
    inputs:
      config-path:
        required: true
        type: string

    secrets:
      repo-token:
        required: true

jobs:
  do-something-else:
    runs-on: ubuntu-latest

    steps:
    - run: echo "Hello v1.0.0"

  add-label:
    runs-on: ubuntu-latest
    steps:
    - name: Github Actions Checkout
      uses: actions/checkout@v4

    - name: Labeler
      uses: actions/labeler@v4.3.0
      with:
        repo-token: ${{ secrets.repo-token }}
        configuration-path: ${{ inputs.config-path }}
        sync-labels: true
